//FilmCard
export const SET_FILM = 'SET_FILM'
export const TOGGLE_FILM_CARD_IS_FETCHING = 'TOGGLE_FILM_CARD_IS_FETCHING'
export const SET_INITIAL_STATE_TO_FILM_CARD = 'SET_INITIAL_STATE_TO_FILM_CARD'

//FilmsPage
export const SET_NOW_PLAYING_FILMS_TO_SLIDER = 'SET_NOW_PLAYING_FILMS_TO_SLIDER'
export const SET_POPULAR_FILMS_TO_SLIDER = 'SET_POPULAR_FILMS_TO_SLIDER'
export const SET_TOP_RATED_FILMS_TO_SLIDER = 'SET_TOP_RATED_FILMS_TO_SLIDER'
export const SET_UPCOMING_FILMS_TO_SLIDER = 'SET_UPCOMING_FILMS_TO_SLIDER'
export const TOGGLE_FILMS_IS_FETCHING = 'TOGGLE_FILMS_IS_FETCHING'
export const SET_INITIAL_STATE_TO_FILMS = 'SET_INITIAL_STATE_TO_FILMS'
export const TOGGLE_IS_FILM_IN_COLLECTION = 'TOGGLE_IS_FILM_IN_COLLECTION'

//HomePage
export const SET_FILMS_TO_SLIDER = 'SET_FILMS_TO_SLIDER'
export const TOGGLE_HOME_IS_FETCHING = 'TOGGLE_HOME_IS_FETCHING'
export const SET_INITIAL_STATE_TO_HOME = 'SET_INITIAL_STATE_TO_HOME'

//Search
export const TOGGLE_SEARCH_BTN = 'TOGGLE_SEARCH_BTN'
export const TOGGLE_SEARCH_IS_FETCHING = 'TOGGLE_SEARCH_IS_FETCHING'
export const TOGGLE_SEARCH_IS_SHOW_RESULTS = 'TOGGLE_SEARCH_IS_SHOW_RESULTS'
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT'
export const SET_SEARCH_TOTAL_RESULTS = 'SET_SEARCH_TOTAL_RESULTS'
export const SET_SEARCH_TOTAL_PAGES = 'SET_SEARCH_TOTAL_PAGES'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const SET_SEARCH_INITIAL_STATE = 'SET_SEARCH_INITIAL_STATE'
export const SET_SEARCH_CURRENT_PAGE = 'SET_SEARCH_CURRENT_PAGE'

//SerialsPage
export const SET_INITIAL_STATE_TO_SERIALS = 'SET_INITIAL_STATE_TO_SERIALS'
export const TOGGLE_IS_SERIALS_FETCHING = 'TOGGLE_IS_SERIALS_FETCHING'
export const SET_POPULAR_TVS_TO_SLIDER = 'SET_POPULAR_TVS_TO_SLIDER'
export const SET_TOP_RATED_TVS_TO_SLIDER = 'SET_TOP_RATED_TVS_TO_SLIDER'
export const SET_ON_AIR_TVS_TO_SLIDER  = 'SET_ON_AIR_TVS_TO_SLIDER'
export const SET_AIRING_TODAY_TVS_TO_SLIDER = 'SET_AIRING_TODAY_TVS_TO_SLIDER'
export const SET_FILM_TYPE = 'SET_FILM_TYPE'

//My Collection
export const SET_FILM_IN_COLLECTION = 'SET_FILM_IN_COLLECTION'
export const REMOVE_FILM_FROM_COLLECTION = 'REMOVE_FILM_FROM_COLLECTION'